version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 10
  pre_build:
    commands:
      - echo `Restore dependencies`
      - dotnet restore
      - dotnet clean

  build:
    commands:
      - dotnet dotnet build
      - dotnet test
      - cd config && cd node result.js
