version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 10
  pre_build:
    commands:
      - echo Restore dependencies
      - dotnet restore
      - dotnet clean

  build:
    commands:
      - dotnet build
      - dotnet test && cd config && npm install --silent
      - node result.js
